version: '3.9'
services:
  api:
    container_name: lockly-bot
    image: lockly-bot:latest
    env_file:
      - ./.env
    networks:
      - lockly-net
    depends_on:
      - 'db'
  db:
    container_name: lockly-db
    image: postgres:13
    expose:
      - 5432
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_USER=lockly
      - POSTGRES_PASSWORD=lockly2023
      - POSGRES_DB=lockly
    networks:
      - lockly-net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "3210:80"
    networks:
      - lockly-net
networks:
  lockly-net:
    name: lockly-net
volumes:
  postgres_volume_local:
    external: true